twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        org_logo: '%env(ORG_LOGO)%'
        org_name: '%env(ORG_NAME)%'
        org_home_text: '%env(ORG_HOME_TEXT)%'

when@test:
    twig:
        strict_variables: true
