twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        org_logo: '%env(ORG_LOGO)%'
        recaptcha3_site_key: '%karser_recaptcha3.site_key%'
        bike_inventory: '@App\Service\BikeInventoryService'
        pages: '@App\Service\PageService'

when@test:
    twig:
        strict_variables: true
