distribution:
    location_days_and_times: "17 Airport Road\nNashua\nMondays from 5 to 7pm"
    policy: "Must have a voucher\nOne bike per year\nIf you miss your appointment, you must reschedule\nMust be 18 or over"