distribution:
    open: '1'
    message: 'We are closed for the season'
    location_days_and_times: "17 Airport Road\nNashua\nMondays from 5 to 7pm"
    policy: "Must have a voucher\nOne bike per year unless you&#039;re really good looking\nIf you miss your appointment, you must reschedule\nMust be 18 or over"
